services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: mydatabasepassword
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mysql   # ใช้ชื่อ 'mysql' ตามที่กำหนดใน services
      DB_USER: user
      DB_PASSWORD: mydatabasepassword
      DB_NAME: mydatabase
      DB_PORT: 3306
    depends_on:
      - mysql

volumes:
  mysql_data:
